// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// EdgeCompanyUsers holds the string denoting the company_users edge name in mutations.
	EdgeCompanyUsers = "company_users"
	// EdgeCreatedDocuments holds the string denoting the created_documents edge name in mutations.
	EdgeCreatedDocuments = "created_documents"
	// EdgeUpdatedDocuments holds the string denoting the updated_documents edge name in mutations.
	EdgeUpdatedDocuments = "updated_documents"
	// Table holds the table name of the user in the database.
	Table = "users"
	// CompanyUsersTable is the table that holds the company_users relation/edge.
	CompanyUsersTable = "company_users"
	// CompanyUsersInverseTable is the table name for the CompanyUser entity.
	// It exists in this package in order to avoid circular dependency with the "companyuser" package.
	CompanyUsersInverseTable = "company_users"
	// CompanyUsersColumn is the table column denoting the company_users relation/edge.
	CompanyUsersColumn = "user_id"
	// CreatedDocumentsTable is the table that holds the created_documents relation/edge.
	CreatedDocumentsTable = "documents"
	// CreatedDocumentsInverseTable is the table name for the Document entity.
	// It exists in this package in order to avoid circular dependency with the "document" package.
	CreatedDocumentsInverseTable = "documents"
	// CreatedDocumentsColumn is the table column denoting the created_documents relation/edge.
	CreatedDocumentsColumn = "created_by"
	// UpdatedDocumentsTable is the table that holds the updated_documents relation/edge.
	UpdatedDocumentsTable = "documents"
	// UpdatedDocumentsInverseTable is the table name for the Document entity.
	// It exists in this package in order to avoid circular dependency with the "document" package.
	UpdatedDocumentsInverseTable = "documents"
	// UpdatedDocumentsColumn is the table column denoting the updated_documents relation/edge.
	UpdatedDocumentsColumn = "updated_by"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPassword,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByCompanyUsersCount orders the results by company_users count.
func ByCompanyUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCompanyUsersStep(), opts...)
	}
}

// ByCompanyUsers orders the results by company_users terms.
func ByCompanyUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompanyUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCreatedDocumentsCount orders the results by created_documents count.
func ByCreatedDocumentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCreatedDocumentsStep(), opts...)
	}
}

// ByCreatedDocuments orders the results by created_documents terms.
func ByCreatedDocuments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedDocumentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUpdatedDocumentsCount orders the results by updated_documents count.
func ByUpdatedDocumentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUpdatedDocumentsStep(), opts...)
	}
}

// ByUpdatedDocuments orders the results by updated_documents terms.
func ByUpdatedDocuments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUpdatedDocumentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCompanyUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompanyUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CompanyUsersTable, CompanyUsersColumn),
	)
}
func newCreatedDocumentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedDocumentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CreatedDocumentsTable, CreatedDocumentsColumn),
	)
}
func newUpdatedDocumentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UpdatedDocumentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UpdatedDocumentsTable, UpdatedDocumentsColumn),
	)
}
