// Code generated by ent, DO NOT EDIT.

package documenttag

import (
	"techmind/schema/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldLTE(FieldID, id))
}

// DocumentID applies equality check predicate on the "document_id" field. It's identical to DocumentIDEQ.
func DocumentID(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldEQ(FieldDocumentID, v))
}

// TagID applies equality check predicate on the "tag_id" field. It's identical to TagIDEQ.
func TagID(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldEQ(FieldTagID, v))
}

// DocumentIDEQ applies the EQ predicate on the "document_id" field.
func DocumentIDEQ(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldEQ(FieldDocumentID, v))
}

// DocumentIDNEQ applies the NEQ predicate on the "document_id" field.
func DocumentIDNEQ(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldNEQ(FieldDocumentID, v))
}

// DocumentIDIn applies the In predicate on the "document_id" field.
func DocumentIDIn(vs ...uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldIn(FieldDocumentID, vs...))
}

// DocumentIDNotIn applies the NotIn predicate on the "document_id" field.
func DocumentIDNotIn(vs ...uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldNotIn(FieldDocumentID, vs...))
}

// DocumentIDGT applies the GT predicate on the "document_id" field.
func DocumentIDGT(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldGT(FieldDocumentID, v))
}

// DocumentIDGTE applies the GTE predicate on the "document_id" field.
func DocumentIDGTE(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldGTE(FieldDocumentID, v))
}

// DocumentIDLT applies the LT predicate on the "document_id" field.
func DocumentIDLT(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldLT(FieldDocumentID, v))
}

// DocumentIDLTE applies the LTE predicate on the "document_id" field.
func DocumentIDLTE(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldLTE(FieldDocumentID, v))
}

// TagIDEQ applies the EQ predicate on the "tag_id" field.
func TagIDEQ(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldEQ(FieldTagID, v))
}

// TagIDNEQ applies the NEQ predicate on the "tag_id" field.
func TagIDNEQ(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldNEQ(FieldTagID, v))
}

// TagIDIn applies the In predicate on the "tag_id" field.
func TagIDIn(vs ...uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldIn(FieldTagID, vs...))
}

// TagIDNotIn applies the NotIn predicate on the "tag_id" field.
func TagIDNotIn(vs ...uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldNotIn(FieldTagID, vs...))
}

// TagIDGT applies the GT predicate on the "tag_id" field.
func TagIDGT(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldGT(FieldTagID, v))
}

// TagIDGTE applies the GTE predicate on the "tag_id" field.
func TagIDGTE(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldGTE(FieldTagID, v))
}

// TagIDLT applies the LT predicate on the "tag_id" field.
func TagIDLT(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldLT(FieldTagID, v))
}

// TagIDLTE applies the LTE predicate on the "tag_id" field.
func TagIDLTE(v uuid.UUID) predicate.DocumentTag {
	return predicate.DocumentTag(sql.FieldLTE(FieldTagID, v))
}

// HasDocument applies the HasEdge predicate on the "document" edge.
func HasDocument() predicate.DocumentTag {
	return predicate.DocumentTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, DocumentTable, DocumentPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentWith applies the HasEdge predicate on the "document" edge with a given conditions (other predicates).
func HasDocumentWith(preds ...predicate.Document) predicate.DocumentTag {
	return predicate.DocumentTag(func(s *sql.Selector) {
		step := newDocumentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTag applies the HasEdge predicate on the "tag" edge.
func HasTag() predicate.DocumentTag {
	return predicate.DocumentTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, TagTable, TagPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagWith applies the HasEdge predicate on the "tag" edge with a given conditions (other predicates).
func HasTagWith(preds ...predicate.Tag) predicate.DocumentTag {
	return predicate.DocumentTag(func(s *sql.Selector) {
		step := newTagStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DocumentTag) predicate.DocumentTag {
	return predicate.DocumentTag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DocumentTag) predicate.DocumentTag {
	return predicate.DocumentTag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DocumentTag) predicate.DocumentTag {
	return predicate.DocumentTag(sql.NotPredicates(p))
}
