version: 3.9.0

tasks:
  tidy:
    desc: Go mod tidy
    cmds:
      - go mod tidy
  nodemon:
    cmds:
      - nodemon --exec "go run cmd/main.go" --ext go .
  start:
    cmds:
      - go run cmd/main.go
  dbgen:
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent generate ./schema --target ./schema/ent --feature sql/modifier,sql/execquery
  dbmc:
    desc: Create migration "task dbmc -- test"
    cmds:
      - goose -dir migrations -s create {{.CLI_ARGS}} sql