// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"techmind/schema/ent/company"
	"techmind/schema/ent/companyuser"
	"techmind/schema/ent/document"
	"techmind/schema/ent/folder"
	"techmind/schema/ent/predicate"
	"techmind/schema/ent/tag"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CompanyQuery is the builder for querying Company entities.
type CompanyQuery struct {
	config
	ctx              *QueryContext
	order            []company.OrderOption
	inters           []Interceptor
	predicates       []predicate.Company
	withCompanyUsers *CompanyUserQuery
	withFolders      *FolderQuery
	withDocuments    *DocumentQuery
	withTags         *TagQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CompanyQuery builder.
func (_q *CompanyQuery) Where(ps ...predicate.Company) *CompanyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CompanyQuery) Limit(limit int) *CompanyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CompanyQuery) Offset(offset int) *CompanyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CompanyQuery) Unique(unique bool) *CompanyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CompanyQuery) Order(o ...company.OrderOption) *CompanyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCompanyUsers chains the current query on the "company_users" edge.
func (_q *CompanyQuery) QueryCompanyUsers() *CompanyUserQuery {
	query := (&CompanyUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(company.Table, company.FieldID, selector),
			sqlgraph.To(companyuser.Table, companyuser.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, company.CompanyUsersTable, company.CompanyUsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFolders chains the current query on the "folders" edge.
func (_q *CompanyQuery) QueryFolders() *FolderQuery {
	query := (&FolderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(company.Table, company.FieldID, selector),
			sqlgraph.To(folder.Table, folder.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, company.FoldersTable, company.FoldersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDocuments chains the current query on the "documents" edge.
func (_q *CompanyQuery) QueryDocuments() *DocumentQuery {
	query := (&DocumentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(company.Table, company.FieldID, selector),
			sqlgraph.To(document.Table, document.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, company.DocumentsTable, company.DocumentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTags chains the current query on the "tags" edge.
func (_q *CompanyQuery) QueryTags() *TagQuery {
	query := (&TagClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(company.Table, company.FieldID, selector),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, company.TagsTable, company.TagsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Company entity from the query.
// Returns a *NotFoundError when no Company was found.
func (_q *CompanyQuery) First(ctx context.Context) (*Company, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{company.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CompanyQuery) FirstX(ctx context.Context) *Company {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Company ID from the query.
// Returns a *NotFoundError when no Company ID was found.
func (_q *CompanyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{company.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CompanyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Company entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Company entity is found.
// Returns a *NotFoundError when no Company entities are found.
func (_q *CompanyQuery) Only(ctx context.Context) (*Company, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{company.Label}
	default:
		return nil, &NotSingularError{company.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CompanyQuery) OnlyX(ctx context.Context) *Company {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Company ID in the query.
// Returns a *NotSingularError when more than one Company ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CompanyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{company.Label}
	default:
		err = &NotSingularError{company.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CompanyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Companies.
func (_q *CompanyQuery) All(ctx context.Context) ([]*Company, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Company, *CompanyQuery]()
	return withInterceptors[[]*Company](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CompanyQuery) AllX(ctx context.Context) []*Company {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Company IDs.
func (_q *CompanyQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(company.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CompanyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CompanyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CompanyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CompanyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CompanyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CompanyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CompanyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CompanyQuery) Clone() *CompanyQuery {
	if _q == nil {
		return nil
	}
	return &CompanyQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]company.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Company{}, _q.predicates...),
		withCompanyUsers: _q.withCompanyUsers.Clone(),
		withFolders:      _q.withFolders.Clone(),
		withDocuments:    _q.withDocuments.Clone(),
		withTags:         _q.withTags.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithCompanyUsers tells the query-builder to eager-load the nodes that are connected to
// the "company_users" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CompanyQuery) WithCompanyUsers(opts ...func(*CompanyUserQuery)) *CompanyQuery {
	query := (&CompanyUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCompanyUsers = query
	return _q
}

// WithFolders tells the query-builder to eager-load the nodes that are connected to
// the "folders" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CompanyQuery) WithFolders(opts ...func(*FolderQuery)) *CompanyQuery {
	query := (&FolderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFolders = query
	return _q
}

// WithDocuments tells the query-builder to eager-load the nodes that are connected to
// the "documents" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CompanyQuery) WithDocuments(opts ...func(*DocumentQuery)) *CompanyQuery {
	query := (&DocumentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDocuments = query
	return _q
}

// WithTags tells the query-builder to eager-load the nodes that are connected to
// the "tags" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CompanyQuery) WithTags(opts ...func(*TagQuery)) *CompanyQuery {
	query := (&TagClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTags = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Company.Query().
//		GroupBy(company.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CompanyQuery) GroupBy(field string, fields ...string) *CompanyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CompanyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = company.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Company.Query().
//		Select(company.FieldName).
//		Scan(ctx, &v)
func (_q *CompanyQuery) Select(fields ...string) *CompanySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CompanySelect{CompanyQuery: _q}
	sbuild.label = company.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CompanySelect configured with the given aggregations.
func (_q *CompanyQuery) Aggregate(fns ...AggregateFunc) *CompanySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CompanyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !company.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CompanyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Company, error) {
	var (
		nodes       = []*Company{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withCompanyUsers != nil,
			_q.withFolders != nil,
			_q.withDocuments != nil,
			_q.withTags != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Company).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Company{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCompanyUsers; query != nil {
		if err := _q.loadCompanyUsers(ctx, query, nodes,
			func(n *Company) { n.Edges.CompanyUsers = []*CompanyUser{} },
			func(n *Company, e *CompanyUser) { n.Edges.CompanyUsers = append(n.Edges.CompanyUsers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFolders; query != nil {
		if err := _q.loadFolders(ctx, query, nodes,
			func(n *Company) { n.Edges.Folders = []*Folder{} },
			func(n *Company, e *Folder) { n.Edges.Folders = append(n.Edges.Folders, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDocuments; query != nil {
		if err := _q.loadDocuments(ctx, query, nodes,
			func(n *Company) { n.Edges.Documents = []*Document{} },
			func(n *Company, e *Document) { n.Edges.Documents = append(n.Edges.Documents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTags; query != nil {
		if err := _q.loadTags(ctx, query, nodes,
			func(n *Company) { n.Edges.Tags = []*Tag{} },
			func(n *Company, e *Tag) { n.Edges.Tags = append(n.Edges.Tags, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CompanyQuery) loadCompanyUsers(ctx context.Context, query *CompanyUserQuery, nodes []*Company, init func(*Company), assign func(*Company, *CompanyUser)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Company)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(companyuser.FieldCompanyID)
	}
	query.Where(predicate.CompanyUser(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(company.CompanyUsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CompanyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "company_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CompanyQuery) loadFolders(ctx context.Context, query *FolderQuery, nodes []*Company, init func(*Company), assign func(*Company, *Folder)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Company)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(folder.FieldCompanyID)
	}
	query.Where(predicate.Folder(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(company.FoldersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CompanyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "company_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CompanyQuery) loadDocuments(ctx context.Context, query *DocumentQuery, nodes []*Company, init func(*Company), assign func(*Company, *Document)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Company)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(document.FieldCompanyID)
	}
	query.Where(predicate.Document(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(company.DocumentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CompanyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "company_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CompanyQuery) loadTags(ctx context.Context, query *TagQuery, nodes []*Company, init func(*Company), assign func(*Company, *Tag)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Company)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tag.FieldCompanyID)
	}
	query.Where(predicate.Tag(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(company.TagsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CompanyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "company_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CompanyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CompanyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(company.Table, company.Columns, sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, company.FieldID)
		for i := range fields {
			if fields[i] != company.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CompanyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(company.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = company.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *CompanyQuery) Modify(modifiers ...func(s *sql.Selector)) *CompanySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// CompanyGroupBy is the group-by builder for Company entities.
type CompanyGroupBy struct {
	selector
	build *CompanyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CompanyGroupBy) Aggregate(fns ...AggregateFunc) *CompanyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CompanyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompanyQuery, *CompanyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CompanyGroupBy) sqlScan(ctx context.Context, root *CompanyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CompanySelect is the builder for selecting fields of Company entities.
type CompanySelect struct {
	*CompanyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CompanySelect) Aggregate(fns ...AggregateFunc) *CompanySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CompanySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompanyQuery, *CompanySelect](ctx, _s.CompanyQuery, _s, _s.inters, v)
}

func (_s *CompanySelect) sqlScan(ctx context.Context, root *CompanyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *CompanySelect) Modify(modifiers ...func(s *sql.Selector)) *CompanySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
