// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"techmind/schema/ent/company"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Company is the model entity for the Company schema.
type Company struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CompanyQuery when eager-loading is set.
	Edges        CompanyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CompanyEdges holds the relations/edges for other nodes in the graph.
type CompanyEdges struct {
	// CompanyUsers holds the value of the company_users edge.
	CompanyUsers []*CompanyUser `json:"company_users,omitempty"`
	// Folders holds the value of the folders edge.
	Folders []*Folder `json:"folders,omitempty"`
	// Documents holds the value of the documents edge.
	Documents []*Document `json:"documents,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CompanyUsersOrErr returns the CompanyUsers value or an error if the edge
// was not loaded in eager-loading.
func (e CompanyEdges) CompanyUsersOrErr() ([]*CompanyUser, error) {
	if e.loadedTypes[0] {
		return e.CompanyUsers, nil
	}
	return nil, &NotLoadedError{edge: "company_users"}
}

// FoldersOrErr returns the Folders value or an error if the edge
// was not loaded in eager-loading.
func (e CompanyEdges) FoldersOrErr() ([]*Folder, error) {
	if e.loadedTypes[1] {
		return e.Folders, nil
	}
	return nil, &NotLoadedError{edge: "folders"}
}

// DocumentsOrErr returns the Documents value or an error if the edge
// was not loaded in eager-loading.
func (e CompanyEdges) DocumentsOrErr() ([]*Document, error) {
	if e.loadedTypes[2] {
		return e.Documents, nil
	}
	return nil, &NotLoadedError{edge: "documents"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e CompanyEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[3] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Company) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case company.FieldName:
			values[i] = new(sql.NullString)
		case company.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Company fields.
func (_m *Company) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case company.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case company.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Company.
// This includes values selected through modifiers, order, etc.
func (_m *Company) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCompanyUsers queries the "company_users" edge of the Company entity.
func (_m *Company) QueryCompanyUsers() *CompanyUserQuery {
	return NewCompanyClient(_m.config).QueryCompanyUsers(_m)
}

// QueryFolders queries the "folders" edge of the Company entity.
func (_m *Company) QueryFolders() *FolderQuery {
	return NewCompanyClient(_m.config).QueryFolders(_m)
}

// QueryDocuments queries the "documents" edge of the Company entity.
func (_m *Company) QueryDocuments() *DocumentQuery {
	return NewCompanyClient(_m.config).QueryDocuments(_m)
}

// QueryTags queries the "tags" edge of the Company entity.
func (_m *Company) QueryTags() *TagQuery {
	return NewCompanyClient(_m.config).QueryTags(_m)
}

// Update returns a builder for updating this Company.
// Note that you need to call Company.Unwrap() before calling this method if this Company
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Company) Update() *CompanyUpdateOne {
	return NewCompanyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Company entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Company) Unwrap() *Company {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Company is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Company) String() string {
	var builder strings.Builder
	builder.WriteString("Company(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Companies is a parsable slice of Company.
type Companies []*Company
