// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"techmind/schema/ent/company"
	"techmind/schema/ent/companyuser"
	"techmind/schema/ent/predicate"
	"techmind/schema/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CompanyUserUpdate is the builder for updating CompanyUser entities.
type CompanyUserUpdate struct {
	config
	hooks     []Hook
	mutation  *CompanyUserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CompanyUserUpdate builder.
func (_u *CompanyUserUpdate) Where(ps ...predicate.CompanyUser) *CompanyUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CompanyUserUpdate) SetUserID(v uuid.UUID) *CompanyUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CompanyUserUpdate) SetNillableUserID(v *uuid.UUID) *CompanyUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *CompanyUserUpdate) SetCompanyID(v uuid.UUID) *CompanyUserUpdate {
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *CompanyUserUpdate) SetNillableCompanyID(v *uuid.UUID) *CompanyUserUpdate {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *CompanyUserUpdate) SetRole(v int) *CompanyUserUpdate {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *CompanyUserUpdate) SetNillableRole(v *int) *CompanyUserUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds value to the "role" field.
func (_u *CompanyUserUpdate) AddRole(v int) *CompanyUserUpdate {
	_u.mutation.AddRole(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CompanyUserUpdate) SetUser(v *User) *CompanyUserUpdate {
	return _u.SetUserID(v.ID)
}

// SetCompany sets the "company" edge to the Company entity.
func (_u *CompanyUserUpdate) SetCompany(v *Company) *CompanyUserUpdate {
	return _u.SetCompanyID(v.ID)
}

// Mutation returns the CompanyUserMutation object of the builder.
func (_u *CompanyUserUpdate) Mutation() *CompanyUserMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CompanyUserUpdate) ClearUser() *CompanyUserUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearCompany clears the "company" edge to the Company entity.
func (_u *CompanyUserUpdate) ClearCompany() *CompanyUserUpdate {
	_u.mutation.ClearCompany()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CompanyUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompanyUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CompanyUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompanyUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompanyUserUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompanyUser.user"`)
	}
	if _u.mutation.CompanyCleared() && len(_u.mutation.CompanyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompanyUser.company"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CompanyUserUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CompanyUserUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CompanyUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(companyuser.Table, companyuser.Columns, sqlgraph.NewFieldSpec(companyuser.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(companyuser.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(companyuser.FieldRole, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   companyuser.UserTable,
			Columns: []string{companyuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   companyuser.UserTable,
			Columns: []string{companyuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CompanyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   companyuser.CompanyTable,
			Columns: []string{companyuser.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   companyuser.CompanyTable,
			Columns: []string{companyuser.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{companyuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CompanyUserUpdateOne is the builder for updating a single CompanyUser entity.
type CompanyUserUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CompanyUserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *CompanyUserUpdateOne) SetUserID(v uuid.UUID) *CompanyUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CompanyUserUpdateOne) SetNillableUserID(v *uuid.UUID) *CompanyUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *CompanyUserUpdateOne) SetCompanyID(v uuid.UUID) *CompanyUserUpdateOne {
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *CompanyUserUpdateOne) SetNillableCompanyID(v *uuid.UUID) *CompanyUserUpdateOne {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *CompanyUserUpdateOne) SetRole(v int) *CompanyUserUpdateOne {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *CompanyUserUpdateOne) SetNillableRole(v *int) *CompanyUserUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds value to the "role" field.
func (_u *CompanyUserUpdateOne) AddRole(v int) *CompanyUserUpdateOne {
	_u.mutation.AddRole(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CompanyUserUpdateOne) SetUser(v *User) *CompanyUserUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetCompany sets the "company" edge to the Company entity.
func (_u *CompanyUserUpdateOne) SetCompany(v *Company) *CompanyUserUpdateOne {
	return _u.SetCompanyID(v.ID)
}

// Mutation returns the CompanyUserMutation object of the builder.
func (_u *CompanyUserUpdateOne) Mutation() *CompanyUserMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CompanyUserUpdateOne) ClearUser() *CompanyUserUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearCompany clears the "company" edge to the Company entity.
func (_u *CompanyUserUpdateOne) ClearCompany() *CompanyUserUpdateOne {
	_u.mutation.ClearCompany()
	return _u
}

// Where appends a list predicates to the CompanyUserUpdate builder.
func (_u *CompanyUserUpdateOne) Where(ps ...predicate.CompanyUser) *CompanyUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CompanyUserUpdateOne) Select(field string, fields ...string) *CompanyUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CompanyUser entity.
func (_u *CompanyUserUpdateOne) Save(ctx context.Context) (*CompanyUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompanyUserUpdateOne) SaveX(ctx context.Context) *CompanyUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CompanyUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompanyUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompanyUserUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompanyUser.user"`)
	}
	if _u.mutation.CompanyCleared() && len(_u.mutation.CompanyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompanyUser.company"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CompanyUserUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CompanyUserUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CompanyUserUpdateOne) sqlSave(ctx context.Context) (_node *CompanyUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(companyuser.Table, companyuser.Columns, sqlgraph.NewFieldSpec(companyuser.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CompanyUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, companyuser.FieldID)
		for _, f := range fields {
			if !companyuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != companyuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(companyuser.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(companyuser.FieldRole, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   companyuser.UserTable,
			Columns: []string{companyuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   companyuser.UserTable,
			Columns: []string{companyuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CompanyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   companyuser.CompanyTable,
			Columns: []string{companyuser.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   companyuser.CompanyTable,
			Columns: []string{companyuser.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CompanyUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{companyuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
