// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"techmind/schema/ent/company"
	"techmind/schema/ent/companyuser"
	"techmind/schema/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// CompanyUser is the model entity for the CompanyUser schema.
type CompanyUser struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CompanyID holds the value of the "company_id" field.
	CompanyID uuid.UUID `json:"company_id,omitempty"`
	// Role holds the value of the "role" field.
	Role int `json:"role,omitempty"`
	// AddedAt holds the value of the "added_at" field.
	AddedAt time.Time `json:"added_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CompanyUserQuery when eager-loading is set.
	Edges        CompanyUserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CompanyUserEdges holds the relations/edges for other nodes in the graph.
type CompanyUserEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Company holds the value of the company edge.
	Company *Company `json:"company,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CompanyUserEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CompanyOrErr returns the Company value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CompanyUserEdges) CompanyOrErr() (*Company, error) {
	if e.Company != nil {
		return e.Company, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: company.Label}
	}
	return nil, &NotLoadedError{edge: "company"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CompanyUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case companyuser.FieldRole:
			values[i] = new(sql.NullInt64)
		case companyuser.FieldAddedAt:
			values[i] = new(sql.NullTime)
		case companyuser.FieldID, companyuser.FieldUserID, companyuser.FieldCompanyID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CompanyUser fields.
func (_m *CompanyUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case companyuser.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case companyuser.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case companyuser.FieldCompanyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field company_id", values[i])
			} else if value != nil {
				_m.CompanyID = *value
			}
		case companyuser.FieldRole:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = int(value.Int64)
			}
		case companyuser.FieldAddedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field added_at", values[i])
			} else if value.Valid {
				_m.AddedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CompanyUser.
// This includes values selected through modifiers, order, etc.
func (_m *CompanyUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CompanyUser entity.
func (_m *CompanyUser) QueryUser() *UserQuery {
	return NewCompanyUserClient(_m.config).QueryUser(_m)
}

// QueryCompany queries the "company" edge of the CompanyUser entity.
func (_m *CompanyUser) QueryCompany() *CompanyQuery {
	return NewCompanyUserClient(_m.config).QueryCompany(_m)
}

// Update returns a builder for updating this CompanyUser.
// Note that you need to call CompanyUser.Unwrap() before calling this method if this CompanyUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CompanyUser) Update() *CompanyUserUpdateOne {
	return NewCompanyUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CompanyUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CompanyUser) Unwrap() *CompanyUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CompanyUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CompanyUser) String() string {
	var builder strings.Builder
	builder.WriteString("CompanyUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("company_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompanyID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	builder.WriteString("added_at=")
	builder.WriteString(_m.AddedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CompanyUsers is a parsable slice of CompanyUser.
type CompanyUsers []*CompanyUser
