// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"techmind/schema/ent/document"
	"techmind/schema/ent/documenttag"
	"techmind/schema/ent/tag"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentTagCreate is the builder for creating a DocumentTag entity.
type DocumentTagCreate struct {
	config
	mutation *DocumentTagMutation
	hooks    []Hook
}

// SetDocumentID sets the "document_id" field.
func (_c *DocumentTagCreate) SetDocumentID(v uuid.UUID) *DocumentTagCreate {
	_c.mutation.SetDocumentID(v)
	return _c
}

// SetTagID sets the "tag_id" field.
func (_c *DocumentTagCreate) SetTagID(v uuid.UUID) *DocumentTagCreate {
	_c.mutation.SetTagID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentTagCreate) SetID(v uuid.UUID) *DocumentTagCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DocumentTagCreate) SetNillableID(v *uuid.UUID) *DocumentTagCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddDocumentIDs adds the "document" edge to the Document entity by IDs.
func (_c *DocumentTagCreate) AddDocumentIDs(ids ...uuid.UUID) *DocumentTagCreate {
	_c.mutation.AddDocumentIDs(ids...)
	return _c
}

// AddDocument adds the "document" edges to the Document entity.
func (_c *DocumentTagCreate) AddDocument(v ...*Document) *DocumentTagCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDocumentIDs(ids...)
}

// AddTagIDs adds the "tag" edge to the Tag entity by IDs.
func (_c *DocumentTagCreate) AddTagIDs(ids ...uuid.UUID) *DocumentTagCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTag adds the "tag" edges to the Tag entity.
func (_c *DocumentTagCreate) AddTag(v ...*Tag) *DocumentTagCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// Mutation returns the DocumentTagMutation object of the builder.
func (_c *DocumentTagCreate) Mutation() *DocumentTagMutation {
	return _c.mutation
}

// Save creates the DocumentTag in the database.
func (_c *DocumentTagCreate) Save(ctx context.Context) (*DocumentTag, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentTagCreate) SaveX(ctx context.Context) *DocumentTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentTagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentTagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentTagCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := documenttag.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentTagCreate) check() error {
	if _, ok := _c.mutation.DocumentID(); !ok {
		return &ValidationError{Name: "document_id", err: errors.New(`ent: missing required field "DocumentTag.document_id"`)}
	}
	if _, ok := _c.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "DocumentTag.tag_id"`)}
	}
	return nil
}

func (_c *DocumentTagCreate) sqlSave(ctx context.Context) (*DocumentTag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentTagCreate) createSpec() (*DocumentTag, *sqlgraph.CreateSpec) {
	var (
		_node = &DocumentTag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(documenttag.Table, sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DocumentID(); ok {
		_spec.SetField(documenttag.FieldDocumentID, field.TypeUUID, value)
		_node.DocumentID = value
	}
	if value, ok := _c.mutation.TagID(); ok {
		_spec.SetField(documenttag.FieldTagID, field.TypeUUID, value)
		_node.TagID = value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.DocumentTable,
			Columns: documenttag.DocumentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.TagTable,
			Columns: documenttag.TagPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DocumentTagCreateBulk is the builder for creating many DocumentTag entities in bulk.
type DocumentTagCreateBulk struct {
	config
	err      error
	builders []*DocumentTagCreate
}

// Save creates the DocumentTag entities in the database.
func (_c *DocumentTagCreateBulk) Save(ctx context.Context) ([]*DocumentTag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DocumentTag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentTagCreateBulk) SaveX(ctx context.Context) []*DocumentTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentTagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentTagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
