// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"techmind/schema/ent/company"
	"techmind/schema/ent/document"
	"techmind/schema/ent/documenttag"
	"techmind/schema/ent/folder"
	"techmind/schema/ent/sender"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentCreate is the builder for creating a Document entity.
type DocumentCreate struct {
	config
	mutation *DocumentMutation
	hooks    []Hook
}

// SetCompanyID sets the "company_id" field.
func (_c *DocumentCreate) SetCompanyID(v uuid.UUID) *DocumentCreate {
	_c.mutation.SetCompanyID(v)
	return _c
}

// SetFolderID sets the "folder_id" field.
func (_c *DocumentCreate) SetFolderID(v uuid.UUID) *DocumentCreate {
	_c.mutation.SetFolderID(v)
	return _c
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableFolderID(v *uuid.UUID) *DocumentCreate {
	if v != nil {
		_c.SetFolderID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DocumentCreate) SetName(v string) *DocumentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *DocumentCreate) SetFilePath(v string) *DocumentCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetPreviewFilePath sets the "preview_file_path" field.
func (_c *DocumentCreate) SetPreviewFilePath(v string) *DocumentCreate {
	_c.mutation.SetPreviewFilePath(v)
	return _c
}

// SetNillablePreviewFilePath sets the "preview_file_path" field if the given value is not nil.
func (_c *DocumentCreate) SetNillablePreviewFilePath(v *string) *DocumentCreate {
	if v != nil {
		_c.SetPreviewFilePath(*v)
	}
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *DocumentCreate) SetFileSize(v int64) *DocumentCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *DocumentCreate) SetMimeType(v string) *DocumentCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *DocumentCreate) SetChecksum(v string) *DocumentCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetSenderID sets the "sender_id" field.
func (_c *DocumentCreate) SetSenderID(v uuid.UUID) *DocumentCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableSenderID(v *uuid.UUID) *DocumentCreate {
	if v != nil {
		_c.SetSenderID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentCreate) SetCreatedAt(v time.Time) *DocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableCreatedAt(v *time.Time) *DocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentCreate) SetID(v uuid.UUID) *DocumentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableID(v *uuid.UUID) *DocumentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCompany sets the "company" edge to the Company entity.
func (_c *DocumentCreate) SetCompany(v *Company) *DocumentCreate {
	return _c.SetCompanyID(v.ID)
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_c *DocumentCreate) SetFolder(v *Folder) *DocumentCreate {
	return _c.SetFolderID(v.ID)
}

// SetSender sets the "sender" edge to the Sender entity.
func (_c *DocumentCreate) SetSender(v *Sender) *DocumentCreate {
	return _c.SetSenderID(v.ID)
}

// AddDocumentTagIDs adds the "document_tags" edge to the DocumentTag entity by IDs.
func (_c *DocumentCreate) AddDocumentTagIDs(ids ...uuid.UUID) *DocumentCreate {
	_c.mutation.AddDocumentTagIDs(ids...)
	return _c
}

// AddDocumentTags adds the "document_tags" edges to the DocumentTag entity.
func (_c *DocumentCreate) AddDocumentTags(v ...*DocumentTag) *DocumentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDocumentTagIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_c *DocumentCreate) Mutation() *DocumentMutation {
	return _c.mutation
}

// Save creates the Document in the database.
func (_c *DocumentCreate) Save(ctx context.Context) (*Document, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentCreate) SaveX(ctx context.Context) *Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := document.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := document.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentCreate) check() error {
	if _, ok := _c.mutation.CompanyID(); !ok {
		return &ValidationError{Name: "company_id", err: errors.New(`ent: missing required field "Document.company_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Document.name"`)}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "Document.file_path"`)}
	}
	if v, ok := _c.mutation.FilePath(); ok {
		if err := document.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "Document.file_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "Document.file_size"`)}
	}
	if v, ok := _c.mutation.FileSize(); ok {
		if err := document.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`ent: validator failed for field "Document.file_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "Document.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := document.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Document.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "Document.checksum"`)}
	}
	if v, ok := _c.mutation.Checksum(); ok {
		if err := document.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "Document.checksum": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Document.created_at"`)}
	}
	if len(_c.mutation.CompanyIDs()) == 0 {
		return &ValidationError{Name: "company", err: errors.New(`ent: missing required edge "Document.company"`)}
	}
	return nil
}

func (_c *DocumentCreate) sqlSave(ctx context.Context) (*Document, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentCreate) createSpec() (*Document, *sqlgraph.CreateSpec) {
	var (
		_node = &Document{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(document.Table, sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(document.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(document.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.PreviewFilePath(); ok {
		_spec.SetField(document.FieldPreviewFilePath, field.TypeString, value)
		_node.PreviewFilePath = &value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(document.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(document.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(document.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(document.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CompanyTable,
			Columns: []string{document.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CompanyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.FolderTable,
			Columns: []string{document.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FolderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.SenderTable,
			Columns: []string{document.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SenderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DocumentTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   document.DocumentTagsTable,
			Columns: document.DocumentTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DocumentCreateBulk is the builder for creating many Document entities in bulk.
type DocumentCreateBulk struct {
	config
	err      error
	builders []*DocumentCreate
}

// Save creates the Document entities in the database.
func (_c *DocumentCreateBulk) Save(ctx context.Context) ([]*Document, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Document, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentCreateBulk) SaveX(ctx context.Context) []*Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
