// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"techmind/schema/ent/company"
	"techmind/schema/ent/document"
	"techmind/schema/ent/documenttag"
	"techmind/schema/ent/folder"
	"techmind/schema/ent/predicate"
	"techmind/schema/ent/sender"
	"techmind/schema/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentUpdate is the builder for updating Document entities.
type DocumentUpdate struct {
	config
	hooks     []Hook
	mutation  *DocumentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DocumentUpdate builder.
func (_u *DocumentUpdate) Where(ps ...predicate.Document) *DocumentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *DocumentUpdate) SetCompanyID(v uuid.UUID) *DocumentUpdate {
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableCompanyID(v *uuid.UUID) *DocumentUpdate {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *DocumentUpdate) SetFolderID(v uuid.UUID) *DocumentUpdate {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableFolderID(v *uuid.UUID) *DocumentUpdate {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *DocumentUpdate) ClearFolderID() *DocumentUpdate {
	_u.mutation.ClearFolderID()
	return _u
}

// SetName sets the "name" field.
func (_u *DocumentUpdate) SetName(v string) *DocumentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableName(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *DocumentUpdate) SetFilePath(v string) *DocumentUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableFilePath(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetPreviewFilePath sets the "preview_file_path" field.
func (_u *DocumentUpdate) SetPreviewFilePath(v string) *DocumentUpdate {
	_u.mutation.SetPreviewFilePath(v)
	return _u
}

// SetNillablePreviewFilePath sets the "preview_file_path" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillablePreviewFilePath(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetPreviewFilePath(*v)
	}
	return _u
}

// ClearPreviewFilePath clears the value of the "preview_file_path" field.
func (_u *DocumentUpdate) ClearPreviewFilePath() *DocumentUpdate {
	_u.mutation.ClearPreviewFilePath()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *DocumentUpdate) SetFileSize(v int64) *DocumentUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableFileSize(v *int64) *DocumentUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *DocumentUpdate) AddFileSize(v int64) *DocumentUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *DocumentUpdate) SetMimeType(v string) *DocumentUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableMimeType(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *DocumentUpdate) SetChecksum(v string) *DocumentUpdate {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableChecksum(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *DocumentUpdate) SetSenderID(v uuid.UUID) *DocumentUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableSenderID(v *uuid.UUID) *DocumentUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *DocumentUpdate) ClearSenderID() *DocumentUpdate {
	_u.mutation.ClearSenderID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DocumentUpdate) SetCreatedBy(v uuid.UUID) *DocumentUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableCreatedBy(v *uuid.UUID) *DocumentUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DocumentUpdate) ClearCreatedBy() *DocumentUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DocumentUpdate) SetUpdatedBy(v uuid.UUID) *DocumentUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableUpdatedBy(v *uuid.UUID) *DocumentUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DocumentUpdate) ClearUpdatedBy() *DocumentUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DocumentUpdate) SetUpdatedAt(v time.Time) *DocumentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCompany sets the "company" edge to the Company entity.
func (_u *DocumentUpdate) SetCompany(v *Company) *DocumentUpdate {
	return _u.SetCompanyID(v.ID)
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_u *DocumentUpdate) SetFolder(v *Folder) *DocumentUpdate {
	return _u.SetFolderID(v.ID)
}

// SetSender sets the "sender" edge to the Sender entity.
func (_u *DocumentUpdate) SetSender(v *Sender) *DocumentUpdate {
	return _u.SetSenderID(v.ID)
}

// SetCreatedByUserID sets the "created_by_user" edge to the User entity by ID.
func (_u *DocumentUpdate) SetCreatedByUserID(id uuid.UUID) *DocumentUpdate {
	_u.mutation.SetCreatedByUserID(id)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *DocumentUpdate) SetNillableCreatedByUserID(id *uuid.UUID) *DocumentUpdate {
	if id != nil {
		_u = _u.SetCreatedByUserID(*id)
	}
	return _u
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *DocumentUpdate) SetCreatedByUser(v *User) *DocumentUpdate {
	return _u.SetCreatedByUserID(v.ID)
}

// SetUpdatedByUserID sets the "updated_by_user" edge to the User entity by ID.
func (_u *DocumentUpdate) SetUpdatedByUserID(id uuid.UUID) *DocumentUpdate {
	_u.mutation.SetUpdatedByUserID(id)
	return _u
}

// SetNillableUpdatedByUserID sets the "updated_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *DocumentUpdate) SetNillableUpdatedByUserID(id *uuid.UUID) *DocumentUpdate {
	if id != nil {
		_u = _u.SetUpdatedByUserID(*id)
	}
	return _u
}

// SetUpdatedByUser sets the "updated_by_user" edge to the User entity.
func (_u *DocumentUpdate) SetUpdatedByUser(v *User) *DocumentUpdate {
	return _u.SetUpdatedByUserID(v.ID)
}

// AddDocumentTagIDs adds the "document_tags" edge to the DocumentTag entity by IDs.
func (_u *DocumentUpdate) AddDocumentTagIDs(ids ...uuid.UUID) *DocumentUpdate {
	_u.mutation.AddDocumentTagIDs(ids...)
	return _u
}

// AddDocumentTags adds the "document_tags" edges to the DocumentTag entity.
func (_u *DocumentUpdate) AddDocumentTags(v ...*DocumentTag) *DocumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentTagIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_u *DocumentUpdate) Mutation() *DocumentMutation {
	return _u.mutation
}

// ClearCompany clears the "company" edge to the Company entity.
func (_u *DocumentUpdate) ClearCompany() *DocumentUpdate {
	_u.mutation.ClearCompany()
	return _u
}

// ClearFolder clears the "folder" edge to the Folder entity.
func (_u *DocumentUpdate) ClearFolder() *DocumentUpdate {
	_u.mutation.ClearFolder()
	return _u
}

// ClearSender clears the "sender" edge to the Sender entity.
func (_u *DocumentUpdate) ClearSender() *DocumentUpdate {
	_u.mutation.ClearSender()
	return _u
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *DocumentUpdate) ClearCreatedByUser() *DocumentUpdate {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearUpdatedByUser clears the "updated_by_user" edge to the User entity.
func (_u *DocumentUpdate) ClearUpdatedByUser() *DocumentUpdate {
	_u.mutation.ClearUpdatedByUser()
	return _u
}

// ClearDocumentTags clears all "document_tags" edges to the DocumentTag entity.
func (_u *DocumentUpdate) ClearDocumentTags() *DocumentUpdate {
	_u.mutation.ClearDocumentTags()
	return _u
}

// RemoveDocumentTagIDs removes the "document_tags" edge to DocumentTag entities by IDs.
func (_u *DocumentUpdate) RemoveDocumentTagIDs(ids ...uuid.UUID) *DocumentUpdate {
	_u.mutation.RemoveDocumentTagIDs(ids...)
	return _u
}

// RemoveDocumentTags removes "document_tags" edges to DocumentTag entities.
func (_u *DocumentUpdate) RemoveDocumentTags(v ...*DocumentTag) *DocumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DocumentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := document.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentUpdate) check() error {
	if v, ok := _u.mutation.FilePath(); ok {
		if err := document.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "Document.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSize(); ok {
		if err := document.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`ent: validator failed for field "Document.file_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := document.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Document.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checksum(); ok {
		if err := document.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "Document.checksum": %w`, err)}
		}
	}
	if _u.mutation.CompanyCleared() && len(_u.mutation.CompanyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Document.company"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(document.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(document.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.PreviewFilePath(); ok {
		_spec.SetField(document.FieldPreviewFilePath, field.TypeString, value)
	}
	if _u.mutation.PreviewFilePathCleared() {
		_spec.ClearField(document.FieldPreviewFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(document.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(document.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(document.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(document.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(document.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CompanyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CompanyTable,
			Columns: []string{document.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CompanyTable,
			Columns: []string{document.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FolderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.FolderTable,
			Columns: []string{document.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.FolderTable,
			Columns: []string{document.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.SenderTable,
			Columns: []string{document.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sender.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.SenderTable,
			Columns: []string{document.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CreatedByUserTable,
			Columns: []string{document.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CreatedByUserTable,
			Columns: []string{document.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.UpdatedByUserTable,
			Columns: []string{document.UpdatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.UpdatedByUserTable,
			Columns: []string{document.UpdatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   document.DocumentTagsTable,
			Columns: document.DocumentTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentTagsIDs(); len(nodes) > 0 && !_u.mutation.DocumentTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   document.DocumentTagsTable,
			Columns: document.DocumentTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   document.DocumentTagsTable,
			Columns: document.DocumentTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentUpdateOne is the builder for updating a single Document entity.
type DocumentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DocumentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCompanyID sets the "company_id" field.
func (_u *DocumentUpdateOne) SetCompanyID(v uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableCompanyID(v *uuid.UUID) *DocumentUpdateOne {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *DocumentUpdateOne) SetFolderID(v uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableFolderID(v *uuid.UUID) *DocumentUpdateOne {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *DocumentUpdateOne) ClearFolderID() *DocumentUpdateOne {
	_u.mutation.ClearFolderID()
	return _u
}

// SetName sets the "name" field.
func (_u *DocumentUpdateOne) SetName(v string) *DocumentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableName(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *DocumentUpdateOne) SetFilePath(v string) *DocumentUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableFilePath(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetPreviewFilePath sets the "preview_file_path" field.
func (_u *DocumentUpdateOne) SetPreviewFilePath(v string) *DocumentUpdateOne {
	_u.mutation.SetPreviewFilePath(v)
	return _u
}

// SetNillablePreviewFilePath sets the "preview_file_path" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillablePreviewFilePath(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetPreviewFilePath(*v)
	}
	return _u
}

// ClearPreviewFilePath clears the value of the "preview_file_path" field.
func (_u *DocumentUpdateOne) ClearPreviewFilePath() *DocumentUpdateOne {
	_u.mutation.ClearPreviewFilePath()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *DocumentUpdateOne) SetFileSize(v int64) *DocumentUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableFileSize(v *int64) *DocumentUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *DocumentUpdateOne) AddFileSize(v int64) *DocumentUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *DocumentUpdateOne) SetMimeType(v string) *DocumentUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableMimeType(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *DocumentUpdateOne) SetChecksum(v string) *DocumentUpdateOne {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableChecksum(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *DocumentUpdateOne) SetSenderID(v uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableSenderID(v *uuid.UUID) *DocumentUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *DocumentUpdateOne) ClearSenderID() *DocumentUpdateOne {
	_u.mutation.ClearSenderID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DocumentUpdateOne) SetCreatedBy(v uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *DocumentUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DocumentUpdateOne) ClearCreatedBy() *DocumentUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DocumentUpdateOne) SetUpdatedBy(v uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *DocumentUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DocumentUpdateOne) ClearUpdatedBy() *DocumentUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DocumentUpdateOne) SetUpdatedAt(v time.Time) *DocumentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCompany sets the "company" edge to the Company entity.
func (_u *DocumentUpdateOne) SetCompany(v *Company) *DocumentUpdateOne {
	return _u.SetCompanyID(v.ID)
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_u *DocumentUpdateOne) SetFolder(v *Folder) *DocumentUpdateOne {
	return _u.SetFolderID(v.ID)
}

// SetSender sets the "sender" edge to the Sender entity.
func (_u *DocumentUpdateOne) SetSender(v *Sender) *DocumentUpdateOne {
	return _u.SetSenderID(v.ID)
}

// SetCreatedByUserID sets the "created_by_user" edge to the User entity by ID.
func (_u *DocumentUpdateOne) SetCreatedByUserID(id uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetCreatedByUserID(id)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableCreatedByUserID(id *uuid.UUID) *DocumentUpdateOne {
	if id != nil {
		_u = _u.SetCreatedByUserID(*id)
	}
	return _u
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *DocumentUpdateOne) SetCreatedByUser(v *User) *DocumentUpdateOne {
	return _u.SetCreatedByUserID(v.ID)
}

// SetUpdatedByUserID sets the "updated_by_user" edge to the User entity by ID.
func (_u *DocumentUpdateOne) SetUpdatedByUserID(id uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetUpdatedByUserID(id)
	return _u
}

// SetNillableUpdatedByUserID sets the "updated_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableUpdatedByUserID(id *uuid.UUID) *DocumentUpdateOne {
	if id != nil {
		_u = _u.SetUpdatedByUserID(*id)
	}
	return _u
}

// SetUpdatedByUser sets the "updated_by_user" edge to the User entity.
func (_u *DocumentUpdateOne) SetUpdatedByUser(v *User) *DocumentUpdateOne {
	return _u.SetUpdatedByUserID(v.ID)
}

// AddDocumentTagIDs adds the "document_tags" edge to the DocumentTag entity by IDs.
func (_u *DocumentUpdateOne) AddDocumentTagIDs(ids ...uuid.UUID) *DocumentUpdateOne {
	_u.mutation.AddDocumentTagIDs(ids...)
	return _u
}

// AddDocumentTags adds the "document_tags" edges to the DocumentTag entity.
func (_u *DocumentUpdateOne) AddDocumentTags(v ...*DocumentTag) *DocumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentTagIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_u *DocumentUpdateOne) Mutation() *DocumentMutation {
	return _u.mutation
}

// ClearCompany clears the "company" edge to the Company entity.
func (_u *DocumentUpdateOne) ClearCompany() *DocumentUpdateOne {
	_u.mutation.ClearCompany()
	return _u
}

// ClearFolder clears the "folder" edge to the Folder entity.
func (_u *DocumentUpdateOne) ClearFolder() *DocumentUpdateOne {
	_u.mutation.ClearFolder()
	return _u
}

// ClearSender clears the "sender" edge to the Sender entity.
func (_u *DocumentUpdateOne) ClearSender() *DocumentUpdateOne {
	_u.mutation.ClearSender()
	return _u
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *DocumentUpdateOne) ClearCreatedByUser() *DocumentUpdateOne {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearUpdatedByUser clears the "updated_by_user" edge to the User entity.
func (_u *DocumentUpdateOne) ClearUpdatedByUser() *DocumentUpdateOne {
	_u.mutation.ClearUpdatedByUser()
	return _u
}

// ClearDocumentTags clears all "document_tags" edges to the DocumentTag entity.
func (_u *DocumentUpdateOne) ClearDocumentTags() *DocumentUpdateOne {
	_u.mutation.ClearDocumentTags()
	return _u
}

// RemoveDocumentTagIDs removes the "document_tags" edge to DocumentTag entities by IDs.
func (_u *DocumentUpdateOne) RemoveDocumentTagIDs(ids ...uuid.UUID) *DocumentUpdateOne {
	_u.mutation.RemoveDocumentTagIDs(ids...)
	return _u
}

// RemoveDocumentTags removes "document_tags" edges to DocumentTag entities.
func (_u *DocumentUpdateOne) RemoveDocumentTags(v ...*DocumentTag) *DocumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentTagIDs(ids...)
}

// Where appends a list predicates to the DocumentUpdate builder.
func (_u *DocumentUpdateOne) Where(ps ...predicate.Document) *DocumentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentUpdateOne) Select(field string, fields ...string) *DocumentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Document entity.
func (_u *DocumentUpdateOne) Save(ctx context.Context) (*Document, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentUpdateOne) SaveX(ctx context.Context) *Document {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DocumentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := document.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentUpdateOne) check() error {
	if v, ok := _u.mutation.FilePath(); ok {
		if err := document.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "Document.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSize(); ok {
		if err := document.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`ent: validator failed for field "Document.file_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := document.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Document.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checksum(); ok {
		if err := document.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "Document.checksum": %w`, err)}
		}
	}
	if _u.mutation.CompanyCleared() && len(_u.mutation.CompanyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Document.company"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentUpdateOne) sqlSave(ctx context.Context) (_node *Document, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Document.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, document.FieldID)
		for _, f := range fields {
			if !document.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != document.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(document.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(document.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.PreviewFilePath(); ok {
		_spec.SetField(document.FieldPreviewFilePath, field.TypeString, value)
	}
	if _u.mutation.PreviewFilePathCleared() {
		_spec.ClearField(document.FieldPreviewFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(document.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(document.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(document.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(document.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(document.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CompanyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CompanyTable,
			Columns: []string{document.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CompanyTable,
			Columns: []string{document.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FolderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.FolderTable,
			Columns: []string{document.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.FolderTable,
			Columns: []string{document.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.SenderTable,
			Columns: []string{document.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sender.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.SenderTable,
			Columns: []string{document.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CreatedByUserTable,
			Columns: []string{document.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CreatedByUserTable,
			Columns: []string{document.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.UpdatedByUserTable,
			Columns: []string{document.UpdatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.UpdatedByUserTable,
			Columns: []string{document.UpdatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   document.DocumentTagsTable,
			Columns: document.DocumentTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentTagsIDs(); len(nodes) > 0 && !_u.mutation.DocumentTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   document.DocumentTagsTable,
			Columns: document.DocumentTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   document.DocumentTagsTable,
			Columns: document.DocumentTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Document{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
