// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"techmind/schema/ent/company"
	"techmind/schema/ent/document"
	"techmind/schema/ent/folder"
	"techmind/schema/ent/sender"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Document is the model entity for the Document schema.
type Document struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CompanyID holds the value of the "company_id" field.
	CompanyID uuid.UUID `json:"company_id,omitempty"`
	// FolderID holds the value of the "folder_id" field.
	FolderID *uuid.UUID `json:"folder_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// FilePath holds the value of the "file_path" field.
	FilePath string `json:"file_path,omitempty"`
	// PreviewFilePath holds the value of the "preview_file_path" field.
	PreviewFilePath *string `json:"preview_file_path,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize int64 `json:"file_size,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// Checksum holds the value of the "checksum" field.
	Checksum string `json:"checksum,omitempty"`
	// SenderID holds the value of the "sender_id" field.
	SenderID *uuid.UUID `json:"sender_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DocumentQuery when eager-loading is set.
	Edges        DocumentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DocumentEdges holds the relations/edges for other nodes in the graph.
type DocumentEdges struct {
	// Company holds the value of the company edge.
	Company *Company `json:"company,omitempty"`
	// Folder holds the value of the folder edge.
	Folder *Folder `json:"folder,omitempty"`
	// Sender holds the value of the sender edge.
	Sender *Sender `json:"sender,omitempty"`
	// DocumentTags holds the value of the document_tags edge.
	DocumentTags []*DocumentTag `json:"document_tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CompanyOrErr returns the Company value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentEdges) CompanyOrErr() (*Company, error) {
	if e.Company != nil {
		return e.Company, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: company.Label}
	}
	return nil, &NotLoadedError{edge: "company"}
}

// FolderOrErr returns the Folder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentEdges) FolderOrErr() (*Folder, error) {
	if e.Folder != nil {
		return e.Folder, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: folder.Label}
	}
	return nil, &NotLoadedError{edge: "folder"}
}

// SenderOrErr returns the Sender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentEdges) SenderOrErr() (*Sender, error) {
	if e.Sender != nil {
		return e.Sender, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: sender.Label}
	}
	return nil, &NotLoadedError{edge: "sender"}
}

// DocumentTagsOrErr returns the DocumentTags value or an error if the edge
// was not loaded in eager-loading.
func (e DocumentEdges) DocumentTagsOrErr() ([]*DocumentTag, error) {
	if e.loadedTypes[3] {
		return e.DocumentTags, nil
	}
	return nil, &NotLoadedError{edge: "document_tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Document) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case document.FieldFolderID, document.FieldSenderID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case document.FieldFileSize:
			values[i] = new(sql.NullInt64)
		case document.FieldName, document.FieldFilePath, document.FieldPreviewFilePath, document.FieldMimeType, document.FieldChecksum:
			values[i] = new(sql.NullString)
		case document.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case document.FieldID, document.FieldCompanyID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Document fields.
func (_m *Document) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case document.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case document.FieldCompanyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field company_id", values[i])
			} else if value != nil {
				_m.CompanyID = *value
			}
		case document.FieldFolderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field folder_id", values[i])
			} else if value.Valid {
				_m.FolderID = new(uuid.UUID)
				*_m.FolderID = *value.S.(*uuid.UUID)
			}
		case document.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case document.FieldFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_path", values[i])
			} else if value.Valid {
				_m.FilePath = value.String
			}
		case document.FieldPreviewFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preview_file_path", values[i])
			} else if value.Valid {
				_m.PreviewFilePath = new(string)
				*_m.PreviewFilePath = value.String
			}
		case document.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case document.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case document.FieldChecksum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checksum", values[i])
			} else if value.Valid {
				_m.Checksum = value.String
			}
		case document.FieldSenderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field sender_id", values[i])
			} else if value.Valid {
				_m.SenderID = new(uuid.UUID)
				*_m.SenderID = *value.S.(*uuid.UUID)
			}
		case document.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Document.
// This includes values selected through modifiers, order, etc.
func (_m *Document) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCompany queries the "company" edge of the Document entity.
func (_m *Document) QueryCompany() *CompanyQuery {
	return NewDocumentClient(_m.config).QueryCompany(_m)
}

// QueryFolder queries the "folder" edge of the Document entity.
func (_m *Document) QueryFolder() *FolderQuery {
	return NewDocumentClient(_m.config).QueryFolder(_m)
}

// QuerySender queries the "sender" edge of the Document entity.
func (_m *Document) QuerySender() *SenderQuery {
	return NewDocumentClient(_m.config).QuerySender(_m)
}

// QueryDocumentTags queries the "document_tags" edge of the Document entity.
func (_m *Document) QueryDocumentTags() *DocumentTagQuery {
	return NewDocumentClient(_m.config).QueryDocumentTags(_m)
}

// Update returns a builder for updating this Document.
// Note that you need to call Document.Unwrap() before calling this method if this Document
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Document) Update() *DocumentUpdateOne {
	return NewDocumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Document entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Document) Unwrap() *Document {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Document is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Document) String() string {
	var builder strings.Builder
	builder.WriteString("Document(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("company_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompanyID))
	builder.WriteString(", ")
	if v := _m.FolderID; v != nil {
		builder.WriteString("folder_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("file_path=")
	builder.WriteString(_m.FilePath)
	builder.WriteString(", ")
	if v := _m.PreviewFilePath; v != nil {
		builder.WriteString("preview_file_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("checksum=")
	builder.WriteString(_m.Checksum)
	builder.WriteString(", ")
	if v := _m.SenderID; v != nil {
		builder.WriteString("sender_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Documents is a parsable slice of Document.
type Documents []*Document
