// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"techmind/schema/ent/documenttag"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// DocumentTag is the model entity for the DocumentTag schema.
type DocumentTag struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DocumentID holds the value of the "document_id" field.
	DocumentID uuid.UUID `json:"document_id,omitempty"`
	// TagID holds the value of the "tag_id" field.
	TagID uuid.UUID `json:"tag_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DocumentTagQuery when eager-loading is set.
	Edges        DocumentTagEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DocumentTagEdges holds the relations/edges for other nodes in the graph.
type DocumentTagEdges struct {
	// Document holds the value of the document edge.
	Document []*Document `json:"document,omitempty"`
	// Tag holds the value of the tag edge.
	Tag []*Tag `json:"tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DocumentOrErr returns the Document value or an error if the edge
// was not loaded in eager-loading.
func (e DocumentTagEdges) DocumentOrErr() ([]*Document, error) {
	if e.loadedTypes[0] {
		return e.Document, nil
	}
	return nil, &NotLoadedError{edge: "document"}
}

// TagOrErr returns the Tag value or an error if the edge
// was not loaded in eager-loading.
func (e DocumentTagEdges) TagOrErr() ([]*Tag, error) {
	if e.loadedTypes[1] {
		return e.Tag, nil
	}
	return nil, &NotLoadedError{edge: "tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DocumentTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case documenttag.FieldID, documenttag.FieldDocumentID, documenttag.FieldTagID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DocumentTag fields.
func (_m *DocumentTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case documenttag.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case documenttag.FieldDocumentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field document_id", values[i])
			} else if value != nil {
				_m.DocumentID = *value
			}
		case documenttag.FieldTagID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tag_id", values[i])
			} else if value != nil {
				_m.TagID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DocumentTag.
// This includes values selected through modifiers, order, etc.
func (_m *DocumentTag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDocument queries the "document" edge of the DocumentTag entity.
func (_m *DocumentTag) QueryDocument() *DocumentQuery {
	return NewDocumentTagClient(_m.config).QueryDocument(_m)
}

// QueryTag queries the "tag" edge of the DocumentTag entity.
func (_m *DocumentTag) QueryTag() *TagQuery {
	return NewDocumentTagClient(_m.config).QueryTag(_m)
}

// Update returns a builder for updating this DocumentTag.
// Note that you need to call DocumentTag.Unwrap() before calling this method if this DocumentTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DocumentTag) Update() *DocumentTagUpdateOne {
	return NewDocumentTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DocumentTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DocumentTag) Unwrap() *DocumentTag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DocumentTag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DocumentTag) String() string {
	var builder strings.Builder
	builder.WriteString("DocumentTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("document_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocumentID))
	builder.WriteString(", ")
	builder.WriteString("tag_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TagID))
	builder.WriteByte(')')
	return builder.String()
}

// DocumentTags is a parsable slice of DocumentTag.
type DocumentTags []*DocumentTag
