// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"techmind/schema/ent/document"
	"techmind/schema/ent/documenttag"
	"techmind/schema/ent/predicate"
	"techmind/schema/ent/tag"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentTagUpdate is the builder for updating DocumentTag entities.
type DocumentTagUpdate struct {
	config
	hooks     []Hook
	mutation  *DocumentTagMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DocumentTagUpdate builder.
func (_u *DocumentTagUpdate) Where(ps ...predicate.DocumentTag) *DocumentTagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentTagUpdate) SetDocumentID(v uuid.UUID) *DocumentTagUpdate {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentTagUpdate) SetNillableDocumentID(v *uuid.UUID) *DocumentTagUpdate {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *DocumentTagUpdate) SetTagID(v uuid.UUID) *DocumentTagUpdate {
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *DocumentTagUpdate) SetNillableTagID(v *uuid.UUID) *DocumentTagUpdate {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// AddDocumentIDs adds the "document" edge to the Document entity by IDs.
func (_u *DocumentTagUpdate) AddDocumentIDs(ids ...uuid.UUID) *DocumentTagUpdate {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocument adds the "document" edges to the Document entity.
func (_u *DocumentTagUpdate) AddDocument(v ...*Document) *DocumentTagUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// AddTagIDs adds the "tag" edge to the Tag entity by IDs.
func (_u *DocumentTagUpdate) AddTagIDs(ids ...uuid.UUID) *DocumentTagUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTag adds the "tag" edges to the Tag entity.
func (_u *DocumentTagUpdate) AddTag(v ...*Tag) *DocumentTagUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the DocumentTagMutation object of the builder.
func (_u *DocumentTagUpdate) Mutation() *DocumentTagMutation {
	return _u.mutation
}

// ClearDocument clears all "document" edges to the Document entity.
func (_u *DocumentTagUpdate) ClearDocument() *DocumentTagUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// RemoveDocumentIDs removes the "document" edge to Document entities by IDs.
func (_u *DocumentTagUpdate) RemoveDocumentIDs(ids ...uuid.UUID) *DocumentTagUpdate {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocument removes "document" edges to Document entities.
func (_u *DocumentTagUpdate) RemoveDocument(v ...*Document) *DocumentTagUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// ClearTag clears all "tag" edges to the Tag entity.
func (_u *DocumentTagUpdate) ClearTag() *DocumentTagUpdate {
	_u.mutation.ClearTag()
	return _u
}

// RemoveTagIDs removes the "tag" edge to Tag entities by IDs.
func (_u *DocumentTagUpdate) RemoveTagIDs(ids ...uuid.UUID) *DocumentTagUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTag removes "tag" edges to Tag entities.
func (_u *DocumentTagUpdate) RemoveTag(v ...*Tag) *DocumentTagUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentTagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentTagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentTagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentTagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentTagUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentTagUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentTagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(documenttag.Table, documenttag.Columns, sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DocumentID(); ok {
		_spec.SetField(documenttag.FieldDocumentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.TagID(); ok {
		_spec.SetField(documenttag.FieldTagID, field.TypeUUID, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.DocumentTable,
			Columns: documenttag.DocumentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentIDs(); len(nodes) > 0 && !_u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.DocumentTable,
			Columns: documenttag.DocumentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.DocumentTable,
			Columns: documenttag.DocumentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.TagTable,
			Columns: documenttag.TagPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagIDs(); len(nodes) > 0 && !_u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.TagTable,
			Columns: documenttag.TagPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.TagTable,
			Columns: documenttag.TagPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documenttag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentTagUpdateOne is the builder for updating a single DocumentTag entity.
type DocumentTagUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DocumentTagMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentTagUpdateOne) SetDocumentID(v uuid.UUID) *DocumentTagUpdateOne {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentTagUpdateOne) SetNillableDocumentID(v *uuid.UUID) *DocumentTagUpdateOne {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *DocumentTagUpdateOne) SetTagID(v uuid.UUID) *DocumentTagUpdateOne {
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *DocumentTagUpdateOne) SetNillableTagID(v *uuid.UUID) *DocumentTagUpdateOne {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// AddDocumentIDs adds the "document" edge to the Document entity by IDs.
func (_u *DocumentTagUpdateOne) AddDocumentIDs(ids ...uuid.UUID) *DocumentTagUpdateOne {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocument adds the "document" edges to the Document entity.
func (_u *DocumentTagUpdateOne) AddDocument(v ...*Document) *DocumentTagUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// AddTagIDs adds the "tag" edge to the Tag entity by IDs.
func (_u *DocumentTagUpdateOne) AddTagIDs(ids ...uuid.UUID) *DocumentTagUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTag adds the "tag" edges to the Tag entity.
func (_u *DocumentTagUpdateOne) AddTag(v ...*Tag) *DocumentTagUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the DocumentTagMutation object of the builder.
func (_u *DocumentTagUpdateOne) Mutation() *DocumentTagMutation {
	return _u.mutation
}

// ClearDocument clears all "document" edges to the Document entity.
func (_u *DocumentTagUpdateOne) ClearDocument() *DocumentTagUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// RemoveDocumentIDs removes the "document" edge to Document entities by IDs.
func (_u *DocumentTagUpdateOne) RemoveDocumentIDs(ids ...uuid.UUID) *DocumentTagUpdateOne {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocument removes "document" edges to Document entities.
func (_u *DocumentTagUpdateOne) RemoveDocument(v ...*Document) *DocumentTagUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// ClearTag clears all "tag" edges to the Tag entity.
func (_u *DocumentTagUpdateOne) ClearTag() *DocumentTagUpdateOne {
	_u.mutation.ClearTag()
	return _u
}

// RemoveTagIDs removes the "tag" edge to Tag entities by IDs.
func (_u *DocumentTagUpdateOne) RemoveTagIDs(ids ...uuid.UUID) *DocumentTagUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTag removes "tag" edges to Tag entities.
func (_u *DocumentTagUpdateOne) RemoveTag(v ...*Tag) *DocumentTagUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the DocumentTagUpdate builder.
func (_u *DocumentTagUpdateOne) Where(ps ...predicate.DocumentTag) *DocumentTagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentTagUpdateOne) Select(field string, fields ...string) *DocumentTagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DocumentTag entity.
func (_u *DocumentTagUpdateOne) Save(ctx context.Context) (*DocumentTag, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentTagUpdateOne) SaveX(ctx context.Context) *DocumentTag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentTagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentTagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentTagUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentTagUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentTagUpdateOne) sqlSave(ctx context.Context) (_node *DocumentTag, err error) {
	_spec := sqlgraph.NewUpdateSpec(documenttag.Table, documenttag.Columns, sqlgraph.NewFieldSpec(documenttag.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DocumentTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, documenttag.FieldID)
		for _, f := range fields {
			if !documenttag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != documenttag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DocumentID(); ok {
		_spec.SetField(documenttag.FieldDocumentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.TagID(); ok {
		_spec.SetField(documenttag.FieldTagID, field.TypeUUID, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.DocumentTable,
			Columns: documenttag.DocumentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentIDs(); len(nodes) > 0 && !_u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.DocumentTable,
			Columns: documenttag.DocumentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.DocumentTable,
			Columns: documenttag.DocumentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.TagTable,
			Columns: documenttag.TagPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagIDs(); len(nodes) > 0 && !_u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.TagTable,
			Columns: documenttag.TagPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   documenttag.TagTable,
			Columns: documenttag.TagPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DocumentTag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documenttag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
