// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"techmind/schema/ent/company"
	"techmind/schema/ent/document"
	"techmind/schema/ent/folder"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FolderCreate is the builder for creating a Folder entity.
type FolderCreate struct {
	config
	mutation *FolderMutation
	hooks    []Hook
}

// SetCompanyID sets the "company_id" field.
func (_c *FolderCreate) SetCompanyID(v uuid.UUID) *FolderCreate {
	_c.mutation.SetCompanyID(v)
	return _c
}

// SetParentFolderID sets the "parent_folder_id" field.
func (_c *FolderCreate) SetParentFolderID(v uuid.UUID) *FolderCreate {
	_c.mutation.SetParentFolderID(v)
	return _c
}

// SetNillableParentFolderID sets the "parent_folder_id" field if the given value is not nil.
func (_c *FolderCreate) SetNillableParentFolderID(v *uuid.UUID) *FolderCreate {
	if v != nil {
		_c.SetParentFolderID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *FolderCreate) SetName(v string) *FolderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *FolderCreate) SetSize(v int64) *FolderCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *FolderCreate) SetNillableSize(v *int64) *FolderCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetCount sets the "count" field.
func (_c *FolderCreate) SetCount(v int) *FolderCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_c *FolderCreate) SetNillableCount(v *int) *FolderCreate {
	if v != nil {
		_c.SetCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FolderCreate) SetID(v uuid.UUID) *FolderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FolderCreate) SetNillableID(v *uuid.UUID) *FolderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCompany sets the "company" edge to the Company entity.
func (_c *FolderCreate) SetCompany(v *Company) *FolderCreate {
	return _c.SetCompanyID(v.ID)
}

// SetParentID sets the "parent" edge to the Folder entity by ID.
func (_c *FolderCreate) SetParentID(id uuid.UUID) *FolderCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Folder entity by ID if the given value is not nil.
func (_c *FolderCreate) SetNillableParentID(id *uuid.UUID) *FolderCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Folder entity.
func (_c *FolderCreate) SetParent(v *Folder) *FolderCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Folder entity by IDs.
func (_c *FolderCreate) AddChildIDs(ids ...uuid.UUID) *FolderCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Folder entity.
func (_c *FolderCreate) AddChildren(v ...*Folder) *FolderCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (_c *FolderCreate) AddDocumentIDs(ids ...uuid.UUID) *FolderCreate {
	_c.mutation.AddDocumentIDs(ids...)
	return _c
}

// AddDocuments adds the "documents" edges to the Document entity.
func (_c *FolderCreate) AddDocuments(v ...*Document) *FolderCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDocumentIDs(ids...)
}

// Mutation returns the FolderMutation object of the builder.
func (_c *FolderCreate) Mutation() *FolderMutation {
	return _c.mutation
}

// Save creates the Folder in the database.
func (_c *FolderCreate) Save(ctx context.Context) (*Folder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FolderCreate) SaveX(ctx context.Context) *Folder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FolderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FolderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FolderCreate) defaults() {
	if _, ok := _c.mutation.Size(); !ok {
		v := folder.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.Count(); !ok {
		v := folder.DefaultCount
		_c.mutation.SetCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := folder.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FolderCreate) check() error {
	if _, ok := _c.mutation.CompanyID(); !ok {
		return &ValidationError{Name: "company_id", err: errors.New(`ent: missing required field "Folder.company_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Folder.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := folder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Folder.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Folder.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := folder.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "Folder.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Folder.count"`)}
	}
	if v, ok := _c.mutation.Count(); ok {
		if err := folder.CountValidator(v); err != nil {
			return &ValidationError{Name: "count", err: fmt.Errorf(`ent: validator failed for field "Folder.count": %w`, err)}
		}
	}
	if len(_c.mutation.CompanyIDs()) == 0 {
		return &ValidationError{Name: "company", err: errors.New(`ent: missing required edge "Folder.company"`)}
	}
	return nil
}

func (_c *FolderCreate) sqlSave(ctx context.Context) (*Folder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FolderCreate) createSpec() (*Folder, *sqlgraph.CreateSpec) {
	var (
		_node = &Folder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(folder.Table, sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(folder.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(folder.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(folder.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if nodes := _c.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.CompanyTable,
			Columns: []string{folder.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CompanyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: []string{folder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentFolderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.ChildrenTable,
			Columns: []string{folder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.DocumentsTable,
			Columns: []string{folder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FolderCreateBulk is the builder for creating many Folder entities in bulk.
type FolderCreateBulk struct {
	config
	err      error
	builders []*FolderCreate
}

// Save creates the Folder entities in the database.
func (_c *FolderCreateBulk) Save(ctx context.Context) ([]*Folder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Folder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FolderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FolderCreateBulk) SaveX(ctx context.Context) []*Folder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FolderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FolderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
