// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"techmind/schema/ent/company"
	"techmind/schema/ent/document"
	"techmind/schema/ent/folder"
	"techmind/schema/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FolderUpdate is the builder for updating Folder entities.
type FolderUpdate struct {
	config
	hooks     []Hook
	mutation  *FolderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the FolderUpdate builder.
func (_u *FolderUpdate) Where(ps ...predicate.Folder) *FolderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *FolderUpdate) SetCompanyID(v uuid.UUID) *FolderUpdate {
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *FolderUpdate) SetNillableCompanyID(v *uuid.UUID) *FolderUpdate {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// SetParentFolderID sets the "parent_folder_id" field.
func (_u *FolderUpdate) SetParentFolderID(v uuid.UUID) *FolderUpdate {
	_u.mutation.SetParentFolderID(v)
	return _u
}

// SetNillableParentFolderID sets the "parent_folder_id" field if the given value is not nil.
func (_u *FolderUpdate) SetNillableParentFolderID(v *uuid.UUID) *FolderUpdate {
	if v != nil {
		_u.SetParentFolderID(*v)
	}
	return _u
}

// ClearParentFolderID clears the value of the "parent_folder_id" field.
func (_u *FolderUpdate) ClearParentFolderID() *FolderUpdate {
	_u.mutation.ClearParentFolderID()
	return _u
}

// SetName sets the "name" field.
func (_u *FolderUpdate) SetName(v string) *FolderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FolderUpdate) SetNillableName(v *string) *FolderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *FolderUpdate) SetSize(v int64) *FolderUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *FolderUpdate) SetNillableSize(v *int64) *FolderUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *FolderUpdate) AddSize(v int64) *FolderUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetCount sets the "count" field.
func (_u *FolderUpdate) SetCount(v int) *FolderUpdate {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *FolderUpdate) SetNillableCount(v *int) *FolderUpdate {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *FolderUpdate) AddCount(v int) *FolderUpdate {
	_u.mutation.AddCount(v)
	return _u
}

// SetCompany sets the "company" edge to the Company entity.
func (_u *FolderUpdate) SetCompany(v *Company) *FolderUpdate {
	return _u.SetCompanyID(v.ID)
}

// SetParentID sets the "parent" edge to the Folder entity by ID.
func (_u *FolderUpdate) SetParentID(id uuid.UUID) *FolderUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Folder entity by ID if the given value is not nil.
func (_u *FolderUpdate) SetNillableParentID(id *uuid.UUID) *FolderUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Folder entity.
func (_u *FolderUpdate) SetParent(v *Folder) *FolderUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Folder entity by IDs.
func (_u *FolderUpdate) AddChildIDs(ids ...uuid.UUID) *FolderUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Folder entity.
func (_u *FolderUpdate) AddChildren(v ...*Folder) *FolderUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (_u *FolderUpdate) AddDocumentIDs(ids ...uuid.UUID) *FolderUpdate {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the Document entity.
func (_u *FolderUpdate) AddDocuments(v ...*Document) *FolderUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// Mutation returns the FolderMutation object of the builder.
func (_u *FolderUpdate) Mutation() *FolderMutation {
	return _u.mutation
}

// ClearCompany clears the "company" edge to the Company entity.
func (_u *FolderUpdate) ClearCompany() *FolderUpdate {
	_u.mutation.ClearCompany()
	return _u
}

// ClearParent clears the "parent" edge to the Folder entity.
func (_u *FolderUpdate) ClearParent() *FolderUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Folder entity.
func (_u *FolderUpdate) ClearChildren() *FolderUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Folder entities by IDs.
func (_u *FolderUpdate) RemoveChildIDs(ids ...uuid.UUID) *FolderUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Folder entities.
func (_u *FolderUpdate) RemoveChildren(v ...*Folder) *FolderUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (_u *FolderUpdate) ClearDocuments() *FolderUpdate {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (_u *FolderUpdate) RemoveDocumentIDs(ids ...uuid.UUID) *FolderUpdate {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to Document entities.
func (_u *FolderUpdate) RemoveDocuments(v ...*Document) *FolderUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FolderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FolderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FolderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FolderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FolderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := folder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Folder.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := folder.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "Folder.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Count(); ok {
		if err := folder.CountValidator(v); err != nil {
			return &ValidationError{Name: "count", err: fmt.Errorf(`ent: validator failed for field "Folder.count": %w`, err)}
		}
	}
	if _u.mutation.CompanyCleared() && len(_u.mutation.CompanyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Folder.company"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FolderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FolderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FolderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(folder.Table, folder.Columns, sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(folder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(folder.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(folder.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(folder.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(folder.FieldCount, field.TypeInt, value)
	}
	if _u.mutation.CompanyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.CompanyTable,
			Columns: []string{folder.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.CompanyTable,
			Columns: []string{folder.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: []string{folder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: []string{folder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.ChildrenTable,
			Columns: []string{folder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.ChildrenTable,
			Columns: []string{folder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.ChildrenTable,
			Columns: []string{folder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.DocumentsTable,
			Columns: []string{folder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.DocumentsTable,
			Columns: []string{folder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.DocumentsTable,
			Columns: []string{folder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{folder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FolderUpdateOne is the builder for updating a single Folder entity.
type FolderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *FolderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCompanyID sets the "company_id" field.
func (_u *FolderUpdateOne) SetCompanyID(v uuid.UUID) *FolderUpdateOne {
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *FolderUpdateOne) SetNillableCompanyID(v *uuid.UUID) *FolderUpdateOne {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// SetParentFolderID sets the "parent_folder_id" field.
func (_u *FolderUpdateOne) SetParentFolderID(v uuid.UUID) *FolderUpdateOne {
	_u.mutation.SetParentFolderID(v)
	return _u
}

// SetNillableParentFolderID sets the "parent_folder_id" field if the given value is not nil.
func (_u *FolderUpdateOne) SetNillableParentFolderID(v *uuid.UUID) *FolderUpdateOne {
	if v != nil {
		_u.SetParentFolderID(*v)
	}
	return _u
}

// ClearParentFolderID clears the value of the "parent_folder_id" field.
func (_u *FolderUpdateOne) ClearParentFolderID() *FolderUpdateOne {
	_u.mutation.ClearParentFolderID()
	return _u
}

// SetName sets the "name" field.
func (_u *FolderUpdateOne) SetName(v string) *FolderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FolderUpdateOne) SetNillableName(v *string) *FolderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *FolderUpdateOne) SetSize(v int64) *FolderUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *FolderUpdateOne) SetNillableSize(v *int64) *FolderUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *FolderUpdateOne) AddSize(v int64) *FolderUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetCount sets the "count" field.
func (_u *FolderUpdateOne) SetCount(v int) *FolderUpdateOne {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *FolderUpdateOne) SetNillableCount(v *int) *FolderUpdateOne {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *FolderUpdateOne) AddCount(v int) *FolderUpdateOne {
	_u.mutation.AddCount(v)
	return _u
}

// SetCompany sets the "company" edge to the Company entity.
func (_u *FolderUpdateOne) SetCompany(v *Company) *FolderUpdateOne {
	return _u.SetCompanyID(v.ID)
}

// SetParentID sets the "parent" edge to the Folder entity by ID.
func (_u *FolderUpdateOne) SetParentID(id uuid.UUID) *FolderUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Folder entity by ID if the given value is not nil.
func (_u *FolderUpdateOne) SetNillableParentID(id *uuid.UUID) *FolderUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Folder entity.
func (_u *FolderUpdateOne) SetParent(v *Folder) *FolderUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Folder entity by IDs.
func (_u *FolderUpdateOne) AddChildIDs(ids ...uuid.UUID) *FolderUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Folder entity.
func (_u *FolderUpdateOne) AddChildren(v ...*Folder) *FolderUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (_u *FolderUpdateOne) AddDocumentIDs(ids ...uuid.UUID) *FolderUpdateOne {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the Document entity.
func (_u *FolderUpdateOne) AddDocuments(v ...*Document) *FolderUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// Mutation returns the FolderMutation object of the builder.
func (_u *FolderUpdateOne) Mutation() *FolderMutation {
	return _u.mutation
}

// ClearCompany clears the "company" edge to the Company entity.
func (_u *FolderUpdateOne) ClearCompany() *FolderUpdateOne {
	_u.mutation.ClearCompany()
	return _u
}

// ClearParent clears the "parent" edge to the Folder entity.
func (_u *FolderUpdateOne) ClearParent() *FolderUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Folder entity.
func (_u *FolderUpdateOne) ClearChildren() *FolderUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Folder entities by IDs.
func (_u *FolderUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *FolderUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Folder entities.
func (_u *FolderUpdateOne) RemoveChildren(v ...*Folder) *FolderUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (_u *FolderUpdateOne) ClearDocuments() *FolderUpdateOne {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (_u *FolderUpdateOne) RemoveDocumentIDs(ids ...uuid.UUID) *FolderUpdateOne {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to Document entities.
func (_u *FolderUpdateOne) RemoveDocuments(v ...*Document) *FolderUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// Where appends a list predicates to the FolderUpdate builder.
func (_u *FolderUpdateOne) Where(ps ...predicate.Folder) *FolderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FolderUpdateOne) Select(field string, fields ...string) *FolderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Folder entity.
func (_u *FolderUpdateOne) Save(ctx context.Context) (*Folder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FolderUpdateOne) SaveX(ctx context.Context) *Folder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FolderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FolderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FolderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := folder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Folder.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := folder.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "Folder.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Count(); ok {
		if err := folder.CountValidator(v); err != nil {
			return &ValidationError{Name: "count", err: fmt.Errorf(`ent: validator failed for field "Folder.count": %w`, err)}
		}
	}
	if _u.mutation.CompanyCleared() && len(_u.mutation.CompanyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Folder.company"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FolderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FolderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FolderUpdateOne) sqlSave(ctx context.Context) (_node *Folder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(folder.Table, folder.Columns, sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Folder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, folder.FieldID)
		for _, f := range fields {
			if !folder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != folder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(folder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(folder.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(folder.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(folder.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(folder.FieldCount, field.TypeInt, value)
	}
	if _u.mutation.CompanyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.CompanyTable,
			Columns: []string{folder.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.CompanyTable,
			Columns: []string{folder.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: []string{folder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: []string{folder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.ChildrenTable,
			Columns: []string{folder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.ChildrenTable,
			Columns: []string{folder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.ChildrenTable,
			Columns: []string{folder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.DocumentsTable,
			Columns: []string{folder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.DocumentsTable,
			Columns: []string{folder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.DocumentsTable,
			Columns: []string{folder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Folder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{folder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
