// Code generated by ent, DO NOT EDIT.

package ent

import (
	"techmind/schema"
	"techmind/schema/ent/company"
	"techmind/schema/ent/companyuser"
	"techmind/schema/ent/document"
	"techmind/schema/ent/documenttag"
	"techmind/schema/ent/folder"
	"techmind/schema/ent/sender"
	"techmind/schema/ent/tag"
	"techmind/schema/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	companyFields := schema.Company{}.Fields()
	_ = companyFields
	// companyDescName is the schema descriptor for name field.
	companyDescName := companyFields[1].Descriptor()
	// company.NameValidator is a validator for the "name" field. It is called by the builders before save.
	company.NameValidator = companyDescName.Validators[0].(func(string) error)
	// companyDescID is the schema descriptor for id field.
	companyDescID := companyFields[0].Descriptor()
	// company.DefaultID holds the default value on creation for the id field.
	company.DefaultID = companyDescID.Default.(func() uuid.UUID)
	companyuserFields := schema.CompanyUser{}.Fields()
	_ = companyuserFields
	// companyuserDescAddedAt is the schema descriptor for added_at field.
	companyuserDescAddedAt := companyuserFields[4].Descriptor()
	// companyuser.DefaultAddedAt holds the default value on creation for the added_at field.
	companyuser.DefaultAddedAt = companyuserDescAddedAt.Default.(func() time.Time)
	// companyuserDescID is the schema descriptor for id field.
	companyuserDescID := companyuserFields[0].Descriptor()
	// companyuser.DefaultID holds the default value on creation for the id field.
	companyuser.DefaultID = companyuserDescID.Default.(func() uuid.UUID)
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescFilePath is the schema descriptor for file_path field.
	documentDescFilePath := documentFields[4].Descriptor()
	// document.FilePathValidator is a validator for the "file_path" field. It is called by the builders before save.
	document.FilePathValidator = documentDescFilePath.Validators[0].(func(string) error)
	// documentDescFileSize is the schema descriptor for file_size field.
	documentDescFileSize := documentFields[6].Descriptor()
	// document.FileSizeValidator is a validator for the "file_size" field. It is called by the builders before save.
	document.FileSizeValidator = documentDescFileSize.Validators[0].(func(int64) error)
	// documentDescMimeType is the schema descriptor for mime_type field.
	documentDescMimeType := documentFields[7].Descriptor()
	// document.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	document.MimeTypeValidator = documentDescMimeType.Validators[0].(func(string) error)
	// documentDescChecksum is the schema descriptor for checksum field.
	documentDescChecksum := documentFields[8].Descriptor()
	// document.ChecksumValidator is a validator for the "checksum" field. It is called by the builders before save.
	document.ChecksumValidator = documentDescChecksum.Validators[0].(func(string) error)
	// documentDescCreatedAt is the schema descriptor for created_at field.
	documentDescCreatedAt := documentFields[10].Descriptor()
	// document.DefaultCreatedAt holds the default value on creation for the created_at field.
	document.DefaultCreatedAt = documentDescCreatedAt.Default.(func() time.Time)
	// documentDescID is the schema descriptor for id field.
	documentDescID := documentFields[0].Descriptor()
	// document.DefaultID holds the default value on creation for the id field.
	document.DefaultID = documentDescID.Default.(func() uuid.UUID)
	documenttagFields := schema.DocumentTag{}.Fields()
	_ = documenttagFields
	// documenttagDescID is the schema descriptor for id field.
	documenttagDescID := documenttagFields[0].Descriptor()
	// documenttag.DefaultID holds the default value on creation for the id field.
	documenttag.DefaultID = documenttagDescID.Default.(func() uuid.UUID)
	folderFields := schema.Folder{}.Fields()
	_ = folderFields
	// folderDescName is the schema descriptor for name field.
	folderDescName := folderFields[3].Descriptor()
	// folder.NameValidator is a validator for the "name" field. It is called by the builders before save.
	folder.NameValidator = folderDescName.Validators[0].(func(string) error)
	// folderDescSize is the schema descriptor for size field.
	folderDescSize := folderFields[4].Descriptor()
	// folder.DefaultSize holds the default value on creation for the size field.
	folder.DefaultSize = folderDescSize.Default.(int64)
	// folder.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	folder.SizeValidator = folderDescSize.Validators[0].(func(int64) error)
	// folderDescCount is the schema descriptor for count field.
	folderDescCount := folderFields[5].Descriptor()
	// folder.DefaultCount holds the default value on creation for the count field.
	folder.DefaultCount = folderDescCount.Default.(int)
	// folder.CountValidator is a validator for the "count" field. It is called by the builders before save.
	folder.CountValidator = folderDescCount.Validators[0].(func(int) error)
	// folderDescID is the schema descriptor for id field.
	folderDescID := folderFields[0].Descriptor()
	// folder.DefaultID holds the default value on creation for the id field.
	folder.DefaultID = folderDescID.Default.(func() uuid.UUID)
	senderFields := schema.Sender{}.Fields()
	_ = senderFields
	// senderDescName is the schema descriptor for name field.
	senderDescName := senderFields[2].Descriptor()
	// sender.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sender.NameValidator = senderDescName.Validators[0].(func(string) error)
	// senderDescID is the schema descriptor for id field.
	senderDescID := senderFields[0].Descriptor()
	// sender.DefaultID holds the default value on creation for the id field.
	sender.DefaultID = senderDescID.Default.(func() uuid.UUID)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[2].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	// tagDescID is the schema descriptor for id field.
	tagDescID := tagFields[0].Descriptor()
	// tag.DefaultID holds the default value on creation for the id field.
	tag.DefaultID = tagDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
