// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CompaniesColumns holds the columns for the "companies" table.
	CompaniesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
	}
	// CompaniesTable holds the schema information for the "companies" table.
	CompaniesTable = &schema.Table{
		Name:       "companies",
		Columns:    CompaniesColumns,
		PrimaryKey: []*schema.Column{CompaniesColumns[0]},
	}
	// CompanyUsersColumns holds the columns for the "company_users" table.
	CompanyUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeInt},
		{Name: "added_at", Type: field.TypeTime},
		{Name: "company_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// CompanyUsersTable holds the schema information for the "company_users" table.
	CompanyUsersTable = &schema.Table{
		Name:       "company_users",
		Columns:    CompanyUsersColumns,
		PrimaryKey: []*schema.Column{CompanyUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "company_users_companies_company_users",
				Columns:    []*schema.Column{CompanyUsersColumns[3]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "company_users_users_company_users",
				Columns:    []*schema.Column{CompanyUsersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "file_path", Type: field.TypeString},
		{Name: "preview_file_path", Type: field.TypeString, Nullable: true},
		{Name: "file_size", Type: field.TypeInt64},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "checksum", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "company_id", Type: field.TypeUUID},
		{Name: "folder_id", Type: field.TypeUUID, Nullable: true},
		{Name: "sender_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "documents_companies_documents",
				Columns:    []*schema.Column{DocumentsColumns[9]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "documents_folders_documents",
				Columns:    []*schema.Column{DocumentsColumns[10]},
				RefColumns: []*schema.Column{FoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "documents_senders_documents",
				Columns:    []*schema.Column{DocumentsColumns[11]},
				RefColumns: []*schema.Column{SendersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "documents_users_created_documents",
				Columns:    []*schema.Column{DocumentsColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "documents_users_updated_documents",
				Columns:    []*schema.Column{DocumentsColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DocumentTagsColumns holds the columns for the "document_tags" table.
	DocumentTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "document_id", Type: field.TypeUUID},
		{Name: "tag_id", Type: field.TypeUUID},
	}
	// DocumentTagsTable holds the schema information for the "document_tags" table.
	DocumentTagsTable = &schema.Table{
		Name:       "document_tags",
		Columns:    DocumentTagsColumns,
		PrimaryKey: []*schema.Column{DocumentTagsColumns[0]},
	}
	// FoldersColumns holds the columns for the "folders" table.
	FoldersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64, Default: 0},
		{Name: "count", Type: field.TypeInt, Default: 0},
		{Name: "company_id", Type: field.TypeUUID},
		{Name: "parent_folder_id", Type: field.TypeUUID, Nullable: true},
	}
	// FoldersTable holds the schema information for the "folders" table.
	FoldersTable = &schema.Table{
		Name:       "folders",
		Columns:    FoldersColumns,
		PrimaryKey: []*schema.Column{FoldersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "folders_companies_folders",
				Columns:    []*schema.Column{FoldersColumns[4]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "folders_folders_children",
				Columns:    []*schema.Column{FoldersColumns[5]},
				RefColumns: []*schema.Column{FoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SendersColumns holds the columns for the "senders" table.
	SendersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "company_id", Type: field.TypeUUID},
	}
	// SendersTable holds the schema information for the "senders" table.
	SendersTable = &schema.Table{
		Name:       "senders",
		Columns:    SendersColumns,
		PrimaryKey: []*schema.Column{SendersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "senders_companies_senders",
				Columns:    []*schema.Column{SendersColumns[3]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "company_id", Type: field.TypeUUID},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tags_companies_tags",
				Columns:    []*schema.Column{TagsColumns[2]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// DocumentDocumentTagsColumns holds the columns for the "document_document_tags" table.
	DocumentDocumentTagsColumns = []*schema.Column{
		{Name: "document_id", Type: field.TypeUUID},
		{Name: "document_tag_id", Type: field.TypeUUID},
	}
	// DocumentDocumentTagsTable holds the schema information for the "document_document_tags" table.
	DocumentDocumentTagsTable = &schema.Table{
		Name:       "document_document_tags",
		Columns:    DocumentDocumentTagsColumns,
		PrimaryKey: []*schema.Column{DocumentDocumentTagsColumns[0], DocumentDocumentTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_document_tags_document_id",
				Columns:    []*schema.Column{DocumentDocumentTagsColumns[0]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "document_document_tags_document_tag_id",
				Columns:    []*schema.Column{DocumentDocumentTagsColumns[1]},
				RefColumns: []*schema.Column{DocumentTagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TagDocumentTagsColumns holds the columns for the "tag_document_tags" table.
	TagDocumentTagsColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeUUID},
		{Name: "document_tag_id", Type: field.TypeUUID},
	}
	// TagDocumentTagsTable holds the schema information for the "tag_document_tags" table.
	TagDocumentTagsTable = &schema.Table{
		Name:       "tag_document_tags",
		Columns:    TagDocumentTagsColumns,
		PrimaryKey: []*schema.Column{TagDocumentTagsColumns[0], TagDocumentTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_document_tags_tag_id",
				Columns:    []*schema.Column{TagDocumentTagsColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_document_tags_document_tag_id",
				Columns:    []*schema.Column{TagDocumentTagsColumns[1]},
				RefColumns: []*schema.Column{DocumentTagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CompaniesTable,
		CompanyUsersTable,
		DocumentsTable,
		DocumentTagsTable,
		FoldersTable,
		SendersTable,
		TagsTable,
		UsersTable,
		DocumentDocumentTagsTable,
		TagDocumentTagsTable,
	}
)

func init() {
	CompanyUsersTable.ForeignKeys[0].RefTable = CompaniesTable
	CompanyUsersTable.ForeignKeys[1].RefTable = UsersTable
	DocumentsTable.ForeignKeys[0].RefTable = CompaniesTable
	DocumentsTable.ForeignKeys[1].RefTable = FoldersTable
	DocumentsTable.ForeignKeys[2].RefTable = SendersTable
	DocumentsTable.ForeignKeys[3].RefTable = UsersTable
	DocumentsTable.ForeignKeys[4].RefTable = UsersTable
	FoldersTable.ForeignKeys[0].RefTable = CompaniesTable
	FoldersTable.ForeignKeys[1].RefTable = FoldersTable
	SendersTable.ForeignKeys[0].RefTable = CompaniesTable
	TagsTable.ForeignKeys[0].RefTable = CompaniesTable
	DocumentDocumentTagsTable.ForeignKeys[0].RefTable = DocumentsTable
	DocumentDocumentTagsTable.ForeignKeys[1].RefTable = DocumentTagsTable
	TagDocumentTagsTable.ForeignKeys[0].RefTable = TagsTable
	TagDocumentTagsTable.ForeignKeys[1].RefTable = DocumentTagsTable
}
