// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// CompanyUser is the predicate function for companyuser builders.
type CompanyUser func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// DocumentTag is the predicate function for documenttag builders.
type DocumentTag func(*sql.Selector)

// Folder is the predicate function for folder builders.
type Folder func(*sql.Selector)

// Sender is the predicate function for sender builders.
type Sender func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
